# feeder
feeder: feeders.iMiGUE_2.Feeder
train_feeder_args:
  data_path: ./iMiGUE/binary_data_json_iMiGUE
  list_path: ./train_list.json
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False
  repeat: 1
  point_nums: 22

val_feeder_args:
  data_path: ./data/iMiGUE/binary_data_json_iMiGUE
  list_path: ./valid_list.json
  label_path: val
  debug: False
  window_size: 52
  point_nums: 22

test_feeder_args:
  data_path: ./data/iMiGUE/binary_data_json_iMiGUE
  list_path: ./test_list.json
  label_path: test
  debug: False
  window_size: 52
  point_nums: 22

# model
model: model.H2OFormer_e6d2.Model
model_args:
  num_class: 2
  num_point: 22
  num_person: 1
  graph: graph.imigue.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_point: 22
  joint_label: [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
                2,2,2,2,2,
                2,2,2,2,2]

#optim
weight_decay: 0
base_lr: 0.0005
lr_decay_rate: 0.1
step: [110, 120]

# training
device: 0
batch_size: 64
val_batch_size: 128
test_batch_size: 512
num_epoch: 100
nesterov: True
warm_up_epoch: 5
